blogsite/AuthApp/urls.py

from django.contrib import admin
from django.urls import path
from AuthApp import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import include

urlpatterns = [
    
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('changepassword',views.changepassword,name='changepassword'),
    path('reset_password',auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'),name="reset_password"),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),name="password_reset_confirm"),
    path('password_reset_complete',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name="password_reset_complete"),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogsite/blogsite/urls.py
from django.contrib import admin
from django.urls import path
from blogapp import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
from blogapp.views import *
from blogapp.views import CommentView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('create', views.create,name='create'),
    path('',views.read,name='home'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('search',views.search,name='search'),
    path('page1',views.first,name='first'),
    path('category',views.Categories,name='category'),
    path('CategoryBlog<str:tag>' , views.CategoryBlog , name='CategoryBlog'),
    path('CurrentUserProfile',views.CurrentUserProfile , name='CurrentUserProfile'),
    path('CurrentUserProfileUpdate',views.CurrentUserProfileUpdate , name='CurrentUserProfileUpdate'),
    path('UserDataupdate' , views.UserDataupdate,name='UserDataupdate'),
    path('likes<int:id>' , views.Likes , name='likes'),
    path('Comment<int:id>/',CommentView.as_view(), name='Comment'),  
    path("Comment/Update/<int:id>", views.CommentUpdateview, name="CommentUpdate"),
    path("Comment/Delete/<int:id>", views.CommentDeleteview, name="CommentDelete"),
    path("ContactView", views.ContactView, name="ContactView"),
    path('Download/<int:id>' , views.DownloadPdf , name='DownloadPdf'),
    
    

    path('',include('AuthApp.urls')),
    

   


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogsite/AuthApp/models.py
from django.db import models
from .managers import *
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin



   # Your custom user manager implementation here

GENDER_CHOICES = (
    ('Male','Male'),
    ('Female' , 'Female'),
    ('Other','Other'),
)
class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=244, unique=True, null=True)
    email = models.EmailField(('email_address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    first_name = models.CharField(max_length=44 , null=True , blank=True)
    last_name = models.CharField(max_length=44 , null= True , blank=True)
    gender = models.CharField(max_length=44,choices = GENDER_CHOICES , null=True)
    number = models.CharField(max_length=10 , null=True)
    profile = models.ImageField(upload_to='images',null=True)
    

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = CustomUserManager()

    def __str__(self):
        return self.username
    

blogsite/blogapp/models.py
# Create your models here.
from django.db import models
from cloudinary.models import CloudinaryField
from AuthApp.models import CustomUser

    
class tag(models.Model):
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

class blog(models.Model):
    heading = models.CharField(max_length=50)
    image = CloudinaryField('image')
    desc = models.TextField(max_length=1000000)
    upload_on = models.CharField(max_length=50)
    upload_by = models.CharField(max_length=100)
    datefield = models.DateField(auto_now_add=True)
    tag = models.ForeignKey(tag,on_delete=models.CASCADE,null=True)
    likes = models.PositiveIntegerField(default=0 , null=True , blank=True)
    
    def __str__(self):
        return self.heading

class Like(models.Model):
    blog = models.ForeignKey(blog , on_delete=models.CASCADE , null=True)
    user = models.ForeignKey(CustomUser , on_delete=models.CASCADE , null=True) 


class Comments(models.Model):
    user = models.ForeignKey(CustomUser , on_delete=models.CASCADE , null=True , blank=True)
    blog = models.ForeignKey(blog , on_delete=models.CASCADE , null=True)
    comment = models.CharField(max_length=300 , null=True , blank=True)
    parent_comment = models.ForeignKey('self' , on_delete=models.CASCADE , null=True , blank=True , related_name='reply')
    timedata = models.DateTimeField(auto_now_add=True , null=True)
    
    def __str__(self):
        return self.comment    
    
class Contact(models.Model):
    FirstName = models.CharField(max_length=100 )
    LastName = models.CharField(max_length=100)
    email = models.EmailField('email_address')
    Feedback = models.CharField(max_length=10000)
    user_name =  models.ForeignKey(CustomUser , on_delete=models.CASCADE )
    
    def __str__(self):
        return self.user_name.username
     
    
    
    

    
    

    
    
    
    
    
    
    


blogsite/AuthApp/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import *
from django import forms


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        models = CustomUser
        fields = ['email' , 'username']
        
class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = CustomUser
        fields = ['email','username']
        
class CustomUserDataForm(forms.ModelForm):
    gender = forms.ChoiceField(choices=GENDER_CHOICES,widget=forms.RadioSelect)
    number = forms.IntegerField(widget=forms.NumberInput ,)
    class Meta:
        model = CustomUser
        fields = ['email','first_name' ,'last_name'  ,'number' , 'gender']
        
class UserProfileUpdate(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('profile',)
    

blogsite/blogapp/views.py
from typing import Any, Dict
from django.shortcuts import render,redirect , get_object_or_404
from .models import *
from .forms import *
import math ,random
from django.db.models import Q
from django.contrib.auth import update_session_auth_hash,authenticate
from django.contrib.auth.models import User,auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from AuthApp.models import *
from AuthApp.forms import UserProfileUpdate ,CustomUserDataForm
from django.views.generic.base import *
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import *
from django.urls import reverse_lazy
from django.http import HttpResponse 
from xhtml2pdf import pisa


# Create your views here.

# Create your views here.



def read(request):
    read_data = blog.objects.all()
    LikeBlog =  Like.objects.all()
    if request.user in read_data:
        done = 1
    else: 
        done = 0
    
    paginator = Paginator(read_data, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
  
    
    return render(request,'home.html',{'read_data':page_obj , 'done':done , })





# def home(request):
#     if request.user.is_authenticated:
#         data = tut.objects.all()
#         paginator = Paginator(data, 6)
#         page_number = request.GET.get('page')
#         page_obj = paginator.get_page(page_number)
#         return render(request, 'home.html', {'data': page_obj})
#     else:
#         return render(request, 'home.html',)


def create(request):
    if request.method == 'GET':
        form = blogform()
        return render(request,'create.html',{'form':form})
    else:
        form = blogform(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home'  )
        else:
            messages.info(request , form.errors)
            return redirect('create' ,)


def update(request,id):
    if request.method =='GET':
        data = blog.objects.get(id=id)
        form = blogform(instance=data)
        return render(request,'create.html',{'form':form})
    else:
        data = blog.objects.get(id=id)
        form = blogform(request.POST,instance=data)
        if form.is_valid():
            form.save()
            return redirect('home')


def delete(request,id):
    del_data = blog.objects.get(id=id)
    del_data.delete()
    return redirect('home')

    







def search(request):
    inp_search = request.POST['QuerieS']
    print(inp_search)
    read_data = blog.objects.filter(heading__icontains = inp_search)
    paginator = Paginator(read_data, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'home.html',{'Blog':page_obj})


def first(request):
    return render(request,'first.html')



def CurrentUserProfile(request ):
    if request.user.is_authenticated:
        user = CustomUser.objects.get(id=request.user.id)
        Blogs = blog.objects.filter(upload_by__exact = user)
        BlogCount = Blogs.count()
           
        return render(request,'Profiles.html' , {'user':user ,'BlogCount':BlogCount , 'Blogs':Blogs})
        
        
    else:
        return redirect('login')
        
def CurrentUserProfileUpdate(request):
    if request.method == "GET":
        form = UserProfileUpdate()
        User = request.user
        return render(request , 'UserProfileUpdate.html' , {'form':form , 'User':User})
    else:
        form = UserProfileUpdate(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('CurrentUserProfile')
        else:
            messages.error(request , form.errors)
            return redirect('CurrentUserProfileUpdate')

def UserDataupdate(request):
    if request.method == "GET":
        user = request.user
        form = CustomUserDataForm(instance=user)
        return render(request , 'UpdateUser.html' ,{'form':form})
    else:
        form = CustomUserDataForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('CurrentUserProfile')
        else:
            messages.error(request, form.errors)
            return render(request , 'UpdateUser.html' )
        

def Categories(request):
    li = ['https://img.freepik.com/free-vector/vintage-monochrome-skull-pirate-hat_225004-2011.jpg?w=740&t=st=1682749458~exp=1682750058~hmac=9afe5818a9ca506aeb433ce6273739df9124975a851c1003aa8f0944ac68b471' ,'https://mdbootstrap.com/img/new/slides/031.jpg', 'https://mdbootstrap.com/img/new/standard/nature/023.jpg' , 'https://images.unsplash.com/photo-1634840884193-2f6cf2538871?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80'  ]
    AllCategories = tag.objects.all()
    RandomNumber = random.randint(0 ,len(li))
    RandomNumber2 = random.randint(0 ,len(li))
    for i in AllCategories:
        blogimage = blog.objects.filter(tag__title__icontains = i)
        
    AllCategorieslist = zip(AllCategories,li)
    context = {
        'AllCategories':AllCategorieslist,
    }
    return render(request , 'cat.html' , context)

def CategoryBlog(request,tag):
    Blogs = blog.objects.filter(tag__title__icontains = tag)
    return render(request , 'Categoriees.html' , {'Blogs':Blogs ,'tag':tag})

def Likes(request,id):
    if request.user.is_authenticated:
        BlogId = get_object_or_404(blog , id=id)
        like,created = Like.objects.get_or_create( user = request.user , blog = BlogId )
        print(BlogId)
        
        if not created:
            print("Deleting Like")
            like.delete()
            BlogId.likes -= 1
            print("Delete Created")
        else:
            BlogId.likes += 1
            print("Like Created")
            
        BlogId.save()
        return redirect( 'home' )
    else:
        messages.info( request , 'You Should Login before like The Post')
        return redirect( 'home' ,)

# @csrf_exempt
# class CommentsViewT(View):
#     template_name = 'readmore.html'
#     def get(self , request , id , *args , **kwargs ):
#         BlogId = blog.objects.get(id=id)
#         comnt = Comments.objects.all()
#         print(comnt, "Comments")
        
#         form =  CommentForm()
#         print(form)
#         context = {
#           'form': form,
#           'readmore':BlogId
#         }
#         return render(request,self.template_name , context)
    
#     def post(self , request , id , *args , **kwargs):
#         if request.user.is_authenticated:
#             form = CommentForm(request.POST)
#             if form.is_valid():
#                 form.save()
#                 return redirect('readmore')
#             else:
#                 form = CommentForm()
#                 context = {
#                     'form':form
#                 }
#                 return redirect('readmore')
#         else:
#             messages.error(request , 'You Have To Login To Comment Your Post')
#             return redirect('readmore' , id=id)

# class CommentView(View):
#     template_name = 'readmore.html'
#     def get(self , request , id):
#         Blog = blog.objects.get(id=id)
#         BlogComments  = Comments.objects.filter(blog=Blog)
#         Suncomments = Comments.objects.filter(blog=blog, parent_comment__isnull=True)
#         form = CommentForm()
#         context = {
#             'form':form,
#             'readmore':Blog,
#             'BlogComments':BlogComments,
#             'Suncomments':Suncomments,
#         }
#         return render(request  , self.template_name , context)
    
#     def post(self , request , id):
#         Blog = blog.objects.get(id=id)
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.user = request.user
#             comment.blog = Blog
#             comment.save()
#             return redirect('Comment' , id=id)
#         else:
#             comments = Comments.objects.filter(blog=Blog)
#             context = {
#                 'form': form,
#                 'blog': Blog,
#                 'comments': comments,
#             }
#             return render(request, 'blog_detail.html', context)
            
class CommentView(View):
    template_name = 'readmore.html'
    
    def get(self, request, id):
        Blog = blog.objects.get(id=id)
        comments = Comments.objects.filter(blog=Blog, )
        form = CommentForm()
        context = {
            'form': form,
            'readmore': Blog,
            'comments': comments,
        }
        return render(request, self.template_name, context)
    
    def post(self, request, id):
        if request.user.is_authenticated:
            
            Blog = blog.objects.get(id=id)
            form = CommentForm(request.POST)
        
            if form.is_valid():
                comment = form.save(commit=False)
                comment.user = request.user
                comment.blog = Blog
                
                if 'parent_comment' in form.cleaned_data:
                    parent_comment = Comments.objects.get(id=form.cleaned_data['parent_comment'])
                    comment.parent_comment = parent_comment 
                comment.save()
                updated_comment = Comments.objects.get(id=comment.id)
                return redirect('Comment', id=id)
            else:
                comments = Comments.objects.filter(blog=Blog, parent_comment__isnull=True)
                context = {
                    'form': form,
                    'blog': Blog,

blogsite/blogapp/templates/UpdateUser.html
{% extends 'base.html' %}
{% block content %}

<style>
    #id_email,#id_number ,#id_first_name ,#id_last_name{
        width: 100%;
        height: 50px;
    }
</style>
<section class="vh-100" >
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-md-9 col-lg-7 col-xl-5 justify-content-center">
          <div class="card" style="border-radius: 15px; ">
            <div class="card-body p-4">
              <div class="text-black">
                
                <form action="{% url 'UserDataupdate' %}" method="post">
                    {% csrf_token %}
                <div class="flex-grow-1 ms-3">
                  <h5 class="mb-1">{{User.first_name |title }} {{User.last_name |title}}</h5>
                  <h6 class="mb-1" style="color: #2b2a2a; font-size: 1.2rem; font-weight:500;">Upload Data And Submit</h6>
                 
                    <div class="justify-content-start">
                        {{form.as_p}}
                    </div>
                     
                   
                  </div>
                  <div class="d-flex pt-1">
                    <a href="{% url 'CurrentUserProfile' %}" class="btn btn-outline-primary me-1 flex-grow-1">Reset</a>
                    <button type="submit" class="btn btn-primary flex-grow-1">Submit</button>
                  </div>
                </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


{% endblock %}

blogsite/blogapp/templates/changepass.html
<form method="POST">
    {% csrf_token %}
{{cp}}
<button type="submit">changepassword</button>
</form>

blogsite/blogapp/templates/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}


<style>
    .cont{
        color: black;
        font-size: 18px;
        font-family: Georgia, 'Times New Roman', Times, serif;
        background: transparent;
        background-position: center;
        align-items: center;  
    }
    .cont h1{
        font-family: "Tangerine", serif;
        font-weight: 700;
    }
   
</style>
{% include 'navbar.html'   %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <section class="h-100 bg-light">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
              <div class="card card-registration my-4">
                <div class="row g-0">
                  <div class="col-xl-6 d-none d-xl-block">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img4.webp"
                      alt="Sample photo" class="img-fluid"
                      style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem;" />
                  </div>
                  <div class="col-xl-6">
                    <div class="card-body p-md-5 text-black">
                      <h3 class="mb-5 text-uppercase">Blog Data </h3>
      
                      <div class="row">
                        <div class="col-md-6 mb-4">
                            {{ form.heading | as_crispy_field }}
                        </div>
                        <div class="col-md-6 mb-4">
                            {{ form.tag | as_crispy_field }}
                        </div>
                      </div>
      
                      <div class="row">
                        <div class="col-md-12 mb-4">
                            {{ form.image | as_crispy_field }}
                        </div>
                        
                      </div>

                      <div class="row">
                        <div class="col-md-12 mb-4">
                            {{ form.desc | as_crispy_field }}
                        </div>
                      </div>

                      <div class="row">
                        <div class="col-md-12 mb-4">
                            {{ form.upload_on | as_crispy_field }}
                        </div>
                        <div class="col-md-6 mb-4">
                            {{ form.upload_by | as_crispy_field }}
                        </div>
                      </div>
                      <div class="d-flex justify-content-end pt-3">
                        <button type="button" class="btn btn-light btn-lg">Reset all</button>
                        <button type="submit" class="btn btn-warning btn-lg ms-2">Submit form</button>
                      </div>
                      <div class="d-flex justify-content-end pt-3">
                        <a  href="{% url 'home' %}" type="button" class="btn btn-light btn-lg">Back</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% if messages %}
        {% for msg in messages %}
        <div class="text-center text-muted">
          <div class="alert alert-danger">
            <p>{{msg}}</p>
          </div>
        </div>
        {% endfor %}
        {% endif %}
      </section>
</form>

<script>
    let uploadby = document.getElementById("id_upload_by");
    let divuploadby = document.getElementById("div_id_upload_by");
    divuploadby.style.display = "none";
    
    let username = '{{request.user}}'

    document.getElementById("id_upload_by").value = username;

    console.log(uploadby)


</script>




</form>
{% endblock %}







blogsite/blogapp/templates/password_reset_complete.html
{% extends 'base.html' %}

<!-- {% block title %}Password reset complete{% endblock %} -->

{% block content %}
<style>
    .container{
        color: black;
    }
</style>
<section class="fdb-block" data-pg-collapsed>

<div class="container">
<h1>Password reset complete</h1>
<p>Your new password has been set. You can log in now on the <a href="{% url 'login' %}">log in page</a></p>
</div>
</section>
{% endblock %}

blogsite/blogapp/templates/password_reset_done.html
{% extends 'base.html' %}

<!-- {% block title %}Email Sent{% endblock %} -->

{% block content %}
<style>
  .container{
    color: black;
  }
</style>
<section class="fdb-block" data-pg-collapsed>

<div class="container">
  <h1>Check your inbox.</h1>
  <p>We've emailed you instructions for setting your password. You should receive the email shortly!</p>
</div>
</section>
{% endblock %}

blogsite/blogapp/templates/readmore.html
{% extends 'base.html'%}         
{% block card %}
<style>
  #id_comment{
    width: 100%;
    height: 50px;
    padding: 10px;
    overflow-x: scroll;
  }
</style>



<main class="mt-5">
  <div class="container">
    <!--Section: Content-->
    <section>
      <div class="row">
        <div class="col-md-6 gx-5 mb-4">
          <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5" data-mdb-ripple-color="light">
            <img src="{{readmore.image.url}}" class="img-fluid" />
            <a href="#!">
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
            </a>
          </div>
        </div>

        <div class="col-md-6 gx-5 mb-4">
          <h4><strong>{{readmore.heading}}</strong> <a href="{% url 'DownloadPdf' readmore.id %}">
            <button type="button" class="btn btn-outline-success">Download</button>
        </a></h4>
          <p class="text-muted">
            {{readmore.desc}}
          </p>
          <p class="text-muted">
            {{readmore.datefield}} <br>{{readmore.tag}}
            <p><strong>{{readmore.upload_by}}</strong></p>
          </p>
          
          <div class="row" style="z-index: 3;">
            <div class="col-8"></div>
            <div class="col-4">
                {% if messages %}
                        <div class="text-center text-muted " id="message">
                          {% for msg in messages %}
                          <div class="alert alert-danger">
                            <p>{{msg}}</p>
                          </div>
                          {% endfor %}
                        </div>
                    {% endif %}
            </div>
        </div>
        {% if user.username == readmore.upload_by or user.is_superuser %}
          <div class="card-body">
            <a href="{% url 'update' readmore.id %}">
                <button type="button" class="btn btn-outline-primary" >Update Data</button>
            </a>
            <a href="{% url 'delete' readmore.id %}">
                <button type="button" class="btn btn-outline-danger">Delete</button>
            </a>
            
          </div>
          <br>
          <a href="{% url 'home' %}" class="btn btn-outline-secondary">Back</a>
          {% endif %}
      </div>
    </section>
  </div>
  <section style="background-color: #f7f6f6;">
    <div class="container my-5 py-5 text-dark">
      <div class="row d-flex justify-content-center">
        <div class="col-md-12 col-lg-10 col-xl-8">
          <div class="d-flex justify-content-between align-items-center mb-4">
            <h4 class="text-dark mb-0">Comments</h4>
            <div class="card">
              <div class="card-body p-2 d-flex align-items-center">
                <h6 class="text-primary fw-bold small mb-0 me-1">Comments "ON"</h6>
                <div class="form-check form-switch">
                  <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked />
                  <label class="form-check-label" for="flexSwitchCheckChecked"></label>
                </div>
              </div>
            </div>
          </div>
       
          {% if comments %}
          {% for comment in comments %}
          <div class="card mb-3">
            <div class="card-body">
              <div class="d-flex flex-start">
                {% if comment.user.profile  %}
                <img class="rounded-circle shadow-1-strong me-3"
                  src="{{comment.user.profile.url}}" alt="avatar" width="40"
                  height="40" />
                {% else %}
                <img class="rounded-circle shadow-1-strong me-3"
                  src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(26).webp" alt="avatar" width="40"
                  height="40" />
                {% endif %}
                <div class="w-100">
                  <div class="d-flex justify-content-between align-items-center mb-3">
                    <h6 class="text-primary fw-bold mb-0">
                      {{comment.user}}
                      <span class="text-dark ms-2">
                        {{comment.comment}}
                      </span>
                      
                    </h6>
                    <p class="mb-0">{{comment.timedata.date}}</p>
                  </div>
                  <div class="d-flex justify-content-between align-items-center">
                    {% if request.user.is_authenticated and comment.user == request.user %}
                    <p class="small mb-0" style="color: #aaa;">
                      <a href="{% url 'CommentDelete' comment.id %}" class="link-grey">Remove</a> •
                      <a href="{% url 'CommentUpdate' comment.id  %}" class="link-grey">Update</a>
                    </p>
                    {% endif %}
                    <div class="d-flex flex-row">
                      <i class="fas fa-star text-warning me-2"></i>
                      <i class="far fa-check-circle" style="color: #aaa;"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          {% endif %}
          <form action="" method="post">
            {% csrf_token %}
            <div class="card mb-3">
              <div class="card-body">
                <div class="d-flex flex-start">
                  {% if comment.user.profile  %}
                  <img class="rounded-circle shadow-1-strong me-3"
                    src="{{comment.user.profile.url}}" alt="avatar" width="40"
                    height="40" />
                  {% else %}
                  <img class="rounded-circle shadow-1-strong me-3"
                    src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(26).webp" alt="avatar" width="40"
                    height="40" />
                  {% endif %}
                  <div class="w-100">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                      
                        {{form.comment}}
                        {{form.parent_comment}}
                        
                        
                     
                      <p class="mb-0">{{form.timedata}}</p>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                      <p class="small mb-0" style="color: #aaa;">
                        <button href="submit" class="btn btn-outline-primary">Post Comment</button> 
                        
                      </p>
                      <div class="d-flex flex-row">
                        <i class="fas fa-star text-warning me-2"></i>
                        <i class="far fa-check-circle" style="color: #aaa;"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}